#!/bin/bash
#PBS -l walltime=12:00:00
#PBS -q parallel
#PBS -l cput=72:00:00
#PBS -l nodes=3:ppn=2

cd $PBS_O_WORKDIR
umask 027

cat $PBS_NODEFILE > NODEFILE
nodes=`cat $PBS_NODEFILE | tr -s '\n' ' '`
NUM_PROCESSES=$(cat $PBS_NODEFILE | wc -l)
NUM_NODES=`cat $PBS_NODEFILE | sort -u | wc -l`

JOBINFO=mpi.np${PBS_NCPUS}_n${NUM_NODES}.${PBS_JOBID}
date > $JOBINFO
echo "Current working directory is `pwd`" >> $JOBINFO
echo "nodes: $nodes" >> $JOBINFO
echo "Running on $NUM_PROCESSES processors on $NUM_NODES nodes." >> $JOBINFO

export CFLAGS="-I/usr/support/common/people/darach/OPENMPI/1.2.8/include -DMPI2 "
export LDFLAGS="-L/usr/support/common/people/darach/OPENMPI/1.2.8/lib -L/usr/support/common/people/darach/OPENMPI/1.2.8/lib/openmpi"
export MPI_ROOT="/usr/support/common/people/darach/OPENMPI/1.2.8/"

export PATH=/usr/support/common/people/darach/R-PROJECT/2.8.0/bin:/usr/support/common/people/darach/OPENMPI/1.2.8/bin:$PATH
export LD_LIBRARY_PATH=/usr/support/common/people/darach/OPENMPI/1.2.8/lib:$LD_LIBRARY_PATH

mpiexec -n 1 Rscript ./analysis/assortativity-analysis.R

echo "Job finished at `date`" >> $JOBINFO
